# services:
#     nginx:
#         image: nginx:alpine
#         ports:
#             - '80:80'
#         volumes:
#             - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
#         depends_on:
#             - php
#     postgres:
#         image: postgres:11
#         environment:
#             - POSTGRES_USER=*****
#             - POSTGRES_PASSWORD=*****
#             - POSTGRES_DB=*****
#         ports:
#             - '5432:5432'
#     php:
#         build: docker/php
#         ports:
#             - '9000:9000'
#         volumes:
#             - ./app:/
#         depends_on:
#             - postgres
version: "2"
services:
    # www:
    #     build: .
    #     ports: 
    #         - "8001:80"
    #     volumes:
    #         - ./www:/var/www/html/
    #     links:
    #         - postgres
    #     networks:
    #         - default
    php:
        image: php:7.1-fpm
        build: .
        ports:
          - 80:80
        volumes:
          - ./www:/var/www/html/
        networks:
          - default
        links:
          - postgres   
    postgres:
        image: postgres:11
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=user
            - POSTGRES_DB=teststage
        ports:
            - '5431:5432'
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     links: 
    #         - db:db
    #     ports:
    #         - 8000:80
    #     environment:
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: test
    #         MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: